package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"sync"

	"github.com/wailsapp/wails/v2/pkg/runtime"

	"github.com/MinhChau9208/NightreignCompanion/internal/fps"
	"github.com/MinhChau9208/NightreignCompanion/internal/gamenet"
	"github.com/MinhChau9208/NightreignCompanion/internal/helper"
	"github.com/MinhChau9208/NightreignCompanion/internal/ipc"
)

// fpsHelper tracks the elevated helper process (same exe, --fps-helper).
// Besides FPS it also watches the game's network connections.
type fpsHelper struct {
	mu      sync.Mutex
	running bool
}

// helperArgs builds the helper's command line. Every value is validated
// (the process name by config, address/token are generated by ipc), so
// none of them can contain spaces or quotes.
func helperArgs(hub *ipc.Server, process string) string {
	return fmt.Sprintf("--fps-helper --ipc-addr %s --ipc-token %s --process %s", hub.Addr(), hub.Token(), process)
}

// StartFPS launches the FPS helper through a UAC prompt.
func (a *App) StartFPS() error {
	if a.mode != ModeMain {
		return errNotMain
	}
	if a.hub == nil {
		return a.initErr
	}
	a.fps.mu.Lock()
	if a.fps.running {
		a.fps.mu.Unlock()
		return nil
	}
	a.fps.running = true // reserve before the (blocking) UAC prompt
	a.fps.mu.Unlock()

	exe, err := os.Executable()
	var proc *fps.Proc
	if err == nil {
		proc, err = fps.LaunchElevated(exe, helperArgs(a.hub, a.cfg.Get().FPS.Process))
	}
	if err != nil {
		a.setFPSRunning(false)
		if errors.Is(err, fps.ErrCancelled) {
			return err
		}
		return fmt.Errorf("start FPS helper: %w", err)
	}
	runtime.EventsEmit(a.ctx, "fps:state", true)
	go func() {
		proc.Wait()
		a.setFPSRunning(false)
	}()
	return nil
}

func (a *App) setFPSRunning(on bool) {
	a.fps.mu.Lock()
	a.fps.running = on
	a.fps.mu.Unlock()
	runtime.EventsEmit(a.ctx, "fps:state", on)
	if !on {
		a.hub.Publish("fps:state", false)
		a.clearGameNet()
	}
}

// StopFPS asks the helper to exit; "fps:state" false follows when it does.
func (a *App) StopFPS() error {
	if a.mode != ModeMain {
		return errNotMain
	}
	if a.hub == nil {
		return a.initErr
	}
	return a.hub.Publish(helper.MsgStop, nil)
}

func (a *App) FPSRunning() bool {
	a.fps.mu.Lock()
	defer a.fps.mu.Unlock()
	return a.fps.running
}

// onHelperMessage relays helper reports to the window and the overlay.
func (a *App) onHelperMessage(m ipc.Message) {
	switch m.Type {
	case fps.MsgStats:
	case gamenet.MsgStats:
		a.onGameNet(m.Data)
		return
	default:
		log.Printf("ipc: ignoring helper message %q", m.Type)
		return
	}
	var st fps.Status
	if err := json.Unmarshal(m.Data, &st); err != nil {
		log.Printf("ipc: bad fps stats: %v", err)
		return
	}
	runtime.EventsEmit(a.ctx, fps.MsgStats, st)
	a.hub.Publish(fps.MsgStats, st)
}

// runFPSHelper is the entry point of the elevated helper process.
func runFPSHelper(addr, token, process string) error {
	return helper.Run(context.Background(), helper.Config{Addr: addr, Token: token, Process: process})
}
