// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FPSRunning() {
  return window['go']['main']['App']['FPSRunning']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function Mode() {
  return window['go']['main']['App']['Mode']();
}

export function NetStats() {
  return window['go']['main']['App']['NetStats']();
}

export function OverlayRunning() {
  return window['go']['main']['App']['OverlayRunning']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartFPS() {
  return window['go']['main']['App']['StartFPS']();
}

export function StopFPS() {
  return window['go']['main']['App']['StopFPS']();
}

export function ToggleOverlay() {
  return window['go']['main']['App']['ToggleOverlay']();
}
