// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {netmon} from '../models';

export function GetSettings():Promise<config.Settings>;

export function Info():Promise<main.AppInfo>;

export function Mode():Promise<main.Mode>;

export function NetStats():Promise<Array<netmon.Stats>>;

export function OverlayRunning():Promise<boolean>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function ToggleOverlay():Promise<boolean>;
